Ansible
sai-lab/iac-workshop pull request #1
Opened 2021-02-24 11:22 UTC by shiro8945

とりあえず，installのプロトタイプが出来たので確認をお願いします．

2021-02-24 11:26 UTC, i13302 commented
Reviews指定したほうがえんちゃう

2021-02-25 08:47 UTC, guni1192 requested changes
YAMLの記法まで書いてくれてありがと．
いくつか修正をお願いします 🙇 
README.mdとansible/README.mdの内容がかぶっているので，
READMEには概要とansible/README.mdのリンクだけ貼ってくれたら大丈夫です．
それ以外の修正は以下のコメントを見てください．

2021-02-25 08:47 UTC, guni1192 commented on README.md
> +Ansibleは，Ansible, Inc.により開発され，2012年にリリースされた構成管理ツールである．(2015年にRedHatに買収される)
細かいけど `Red Hat` な
```suggestion
Ansibleは，Ansible, Inc.により開発され，2012年にリリースされた構成管理ツールである．(2015年にRed Hatに買収される)  
```

2021-02-25 08:47 UTC, guni1192 commented on ansible/ansible_structure.txt
> +例 : 〇〇(ファイル)，〇〇/(ディレクトリ)
この内容を`ansible/README.md` 内にかいて，バッククオート3つで囲うと良いと思う．

2021-02-25 08:47 UTC, guni1192 commented on ansible/hosts.sample
> +[install]
Vagrantで構築したVM内部でAnsibleを実行させるならこれで良いと思うんだけど，それじゃエージェントレスであるメリットが薄いと思う．

だからVagrantを実行するVMホストから実行するようにIPを書き換えても良いと思う．
Vagrantfile内部でIPを指定(192.168.xxx.yyy)したらそのIPにこのファイルの中身も書き換えるとかで良いと思う．

2021-02-25 08:47 UTC, guni1192 commented on README.md
> +$ ansible 127.0.0.1 -m ping
ここはIPじゃなくてinventryを指定したほうが良いと思う(例: `-i hosts`)

2021-03-04 08:49 UTC, shiro8945 commented
上記の件修正しました．
レビューありがとうございます。

2021-03-18 12:04 UTC, guni1192 approved these changes

2021-03-18 12:04 UTC, merged