Vagrant
sai-lab/iac-workshop pull request #2
Opened 2021-03-04 08:35 UTC by shiro8945

vagrantを追加したのでレビューお願いします

2021-03-04 10:51 UTC, guni1192 commented
今回の実習環境をKVMにするかVirtualBoxにするかまだ決まってなかった．ごめん．
検証するからちょっとレビューまで時間かかる

2021-03-04 11:04 UTC, shiro8945 commented
kvmだったら，providerの部分をlibvertに変えたらいけると思います．

2021-03-04 11:06 UTC, shiro8945 commented
後は，入ってないんだったら，vagrant-libvert，ruby-libvertのインストールが必要ですね

2021-03-05 09:47 UTC, guni1192 commented
そそ．あとオプションがKVM対応してるものとしてないものがあるので

2021-03-11 05:08 UTC, guni1192 commented
rookieだと流石にVirtualBoxで人数分(6台)のVM収容できないと思うので，KVMにします．
今のrookieだったら検証できると思うからそっちでテストしてくれると助かる

2021-03-12 02:50 UTC, guni1192 requested changes
IaCは動く仕様書として動作する必要があるので，できるだけ動く用にしてほしいです．
例えば，`.sample` などがついているとリネームとかの手間が発生します．
そのため，Vagrantfileに名前変更してください．
あといくつか変更点です．

2021-03-12 02:50 UTC, guni1192 commented on vagrant/Vagrantfile.sample
> +    machine1.vm.box_check_update = false
更新をサジェストしてくれるだけだからonでいいと思う．むしろデフォでonだからこの行書かなくてもいいかな．ややこしくなるだけだし

2021-03-12 02:50 UTC, guni1192 commented on vagrant/Vagrantfile.sample
> +    machine1.vm.network "forwarded_port", guest: 80, host: 8080, id: "http"
共有のサーバでやるからポート固定してここに書いちゃうと一気に立ち上げるときに動かないからとりあえずコメントアウトで

2021-03-12 02:50 UTC, guni1192 commented on vagrant/Vagrantfile.sample
> +    machine1.vm.network "private_network", ip: "192.168.33.10"
この行必要かと思ったけど，KVMだとデフォルトでブリッジに1本NICを生やしてくれるので必要なさそう．この行削除で

2021-03-12 02:50 UTC, guni1192 commented on vagrant/Vagrantfile.sample
> +    end
こんな感じに変更お願いします．

```suggestion
    machine.vm.provider :libvirt do |libvirt|
      libvirt.cpus = 1
      libvirt.memory = 2048
    end
```

2021-03-16 01:54 UTC, guni1192 approved these changes
LGTM

2021-03-16 01:54 UTC, merged